{
 "title": "SENSBEY IOT R2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "ステータスパネル", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ダッシュボード",
   "type": "text",
   "description": "Dashboard",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<iframe src=\"http://192.168.11.124:1880/ui/#!/2?socketid=zR0qurN5Sow2FDeOAAAB\" title=\"W3Schools Free Online Web Tutorials\" width=\"100%\" height=\"100%\" scrolling=\"no\" style=\"overflow:hidden\"></iframe>\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  id\nFROM milesight\nWHERE\n  $__timeFilter(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "温度データ",
   "type": "timeseries",
   "description": "Heater Temp Log",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  temp1 AS \"ヒーター 1\",\n  temp2 AS \"ヒーター 2\",\n  temp3 AS \"ヒーター 3\",\n  temp4 AS \"ヒーター 4\",\n  temp5 AS \"ヒーター 5\",\n  temp6 AS \"ヒーター 6\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  },
  { "title": "コントロールパネル", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "コントロールパネル",
   "type": "text",
   "gridPos": { "h": 22, "w": 21, "x": 0, "y": 33 },
   "options": {
    "content": "<iframe src=\"http://192.168.11.124:1880/ui/#!/0?socketid=zR0qurN5Sow2FDeOAAAB\" title=\"W3Schools Free Online Web Tutorials\" width=\"100%\" height=\"100%\" scrolling=\"no\" style=\"overflow:hidden\"></iframe>\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  id\nFROM milesight\nWHERE\n  $__timeFilter(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "温度校正",
   "type": "stat",
   "description": "Calibration",
   "gridPos": { "h": 22, "w": 3, "x": 21, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cast(calibration1 as float) as \"センサー 1\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration2 as float) as \"センサー 2\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration3 as float) as \"センサー3\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration4 as float) as \"センサー 4\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration5 as float) as \"センサー5\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration6 as float) as \"センサー 6\"\nFROM currentConfig"
    }
   ]
  }
 ]
}