{
 "title": "Temp Monitoring",
 "time": { "from": "2022-11-01T14:58:15.773Z", "to": "2022-11-01T16:10:42.942Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Control Panel",
   "type": "text",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<iframe src=\"http://127.2.2.2:1880/ui/#!/0?socketid=zR0qurN5Sow2FDeOAAAB\" title=\"W3Schools Free Online Web Tutorials\" width=\"100%\" height=\"100%\" scrolling=\"no\" style=\"overflow:hidden\"></iframe>\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  id\nFROM milesight\nWHERE\n  $__timeFilter(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Heater Temperatures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp1 AS \"Heater 1\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp2 AS \"Heater 2\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp3 AS \"Heater 3\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp4 AS \"Heater 4\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp5 AS \"Heater 5\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp6 AS \"Heater 6\"\nFROM tempControlDevice\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Heater Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cast(st1 as float) as \"Heater 1\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st2 as float) as \"Heater 2\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st3 as float) as \"Heater 3\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st4 as float) as \"Heater 4\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st5 as float) as \"Heater 5\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st6 as float) as \"Heater 6\"\nFROM currentConfig"
    }
   ]
  },
  {
   "title": "Calibration Data",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cast(calibration1 as float) as \"Calibration 1\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration2 as float) as \"Calibration 2\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration3 as float) as \"Calibration 3\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration4 as float) as \"Calibration 4\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration5 as float) as \"Calibration 5\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration6 as float) as \"Calibration 6\"\nFROM currentConfig"
    }
   ]
  },
  {
   "title": "Heater Temperatures Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp1) AS \"Heater 1\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp2) AS \"Heater 2\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp3) AS \"Heater 3\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp4) AS \"Heater 4\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp5) AS \"Heater 5\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp6) AS \"Heater 6\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  }
 ]
}