{
 "title": "Temp Monitoring",
 "time": { "from": "2022-11-01T14:58:15.773Z", "to": "2022-11-01T16:10:42.942Z" },
 "refresh": "5s",
 "panels": [
  { "title": "ステータスパネル", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ヒーター温度",
   "type": "stat",
   "description": "Temperature",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp1 AS \"ヒーター 1\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp2 AS \"ヒーター 2\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp3 AS \"ヒーター 3\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp4 AS \"ヒーター4\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp5 AS \"ヒーター5\"\nFROM tempControlDevice\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temp6 AS \"ヒーター6\"\nFROM tempControlDevice\nORDER BY ts"
    }
   ]
  },
  {
   "title": "ヒーターステータス",
   "type": "stat",
   "description": "Heater Status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cast(st1 as float) as \"ヒーター 1\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st2 as float) as \"ヒーター 2\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st3 as float) as \"ヒーター 3\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st4 as float) as \"ヒーター 4\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st5 as float) as \"ヒーター 5\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(st6 as float) as \"ヒーター 6\"\nFROM currentConfig"
    }
   ]
  },
  {
   "title": "Min Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cast(st1min as float) as \"ヒーター 1\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration2 as float) as \"ヒーター 2\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration3 as float) as \"ヒーター 3\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration4 as float) as \"ヒーター 4\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration5 as float) as \"ヒーター 5\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration6 as float) as \"ヒーター 6\"\nFROM currentConfig"
    }
   ]
  },
  {
   "title": "Max Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cast(st1max as float) as \"ヒーター 1\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration2 as float) as \"ヒーター 2\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration3 as float) as \"ヒーター 3\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration4 as float) as \"ヒーター 4\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration5 as float) as \"ヒーター 5\"\nFROM currentConfig"
    },
    {
     "rawSql": "SELECT cast(calibration6 as float) as \"ヒーター 6\"\nFROM currentConfig"
    }
   ]
  },
  {
   "title": "Heater Temperatures Log",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp1) AS \"Heater 1\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp2) AS \"Heater 2\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp3) AS \"Heater 3\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp4) AS \"Heater 4\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp5) AS \"Heater 5\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(temp6) AS \"Heater 6\"\nFROM tempControlDevice\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  },
  {
   "title": "コントロールパネル",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "コントロールパネル",
     "type": "text",
     "gridPos": { "h": 20, "w": 16, "x": 0, "y": 2 },
     "options": {
      "content": "<iframe src=\"http://127.0.0.1:1880/ui/#!/0?socketid=zR0qurN5Sow2FDeOAAAB\" title=\"W3Schools Free Online Web Tutorials\" width=\"100%\" height=\"100%\" scrolling=\"no\" style=\"overflow:hidden\"></iframe>\n"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  updated_at AS \"time\",\n  id\nFROM milesight\nWHERE\n  $__timeFilter(updated_at)\nORDER BY updated_at"
      }
     ]
    },
    {
     "title": "温 度 読 調 整 許 差",
     "type": "stat",
     "gridPos": { "h": 20, "w": 8, "x": 16, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT cast(calibration1 as float) as \"センサー 1\"\nFROM currentConfig"
      },
      {
       "rawSql": "SELECT cast(calibration2 as float) as \"センサー 2\"\nFROM currentConfig"
      },
      {
       "rawSql": "SELECT cast(calibration3 as float) as \"センサー3\"\nFROM currentConfig"
      },
      {
       "rawSql": "SELECT cast(calibration4 as float) as \"センサー 4\"\nFROM currentConfig"
      },
      {
       "rawSql": "SELECT cast(calibration5 as float) as \"センサー5\"\nFROM currentConfig"
      },
      {
       "rawSql": "SELECT cast(calibration6 as float) as \"センサー 6\"\nFROM currentConfig"
      }
     ]
    }
   ]
  }
 ]
}